// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmyzazgwyohmkglnwbyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdteXphemd3eW9obWtnbG53YnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNTk1MzUsImV4cCI6MjA1OTczNTUzNX0.LQEFBtervUoTsMA-chfcCwxbkwXA3uVoejpoXLDCddw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);